name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o secret2env main.go

      - name: Upload release binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            secret2env
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
